#!/usr/bin/env bash
set -euo pipefail

###############################################################################
# deploy.sh - Deploy Azure Blob Storage infrastructure for dex package registry
#
# Usage: ./deploy.sh [RESOURCE_GROUP]
#
# This script:
#   1. Creates the resource group if it doesn't exist
#   2. Deploys the Bicep template for storage + static website hosting
#   3. Retrieves deployment outputs
#   4. Enables static website hosting with index document
#   5. Writes config.sh with exported variables for downstream scripts
###############################################################################

# Resolve the directory this script lives in, so it works from any cwd
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Resource group: first argument or default
RESOURCE_GROUP="${1:-dex-registry-rg}"
LOCATION="eastus"
DEPLOYMENT_NAME="dex-registry-$(date +%Y%m%d%H%M%S)"

TEMPLATE_FILE="${SCRIPT_DIR}/main.bicep"
PARAMETERS_FILE="${SCRIPT_DIR}/parameters.json"
CONFIG_FILE="${SCRIPT_DIR}/config.sh"

echo "============================================"
echo "  Dex Registry - Azure Infrastructure Deploy"
echo "============================================"
echo ""
echo "Resource Group : ${RESOURCE_GROUP}"
echo "Location       : ${LOCATION}"
echo "Template       : ${TEMPLATE_FILE}"
echo "Parameters     : ${PARAMETERS_FILE}"
echo ""

# ---- Step 1: Ensure resource group exists ------------------------------------
echo "[1/5] Checking resource group '${RESOURCE_GROUP}'..."
if az group show --name "${RESOURCE_GROUP}" &>/dev/null; then
  echo "       Resource group already exists."
else
  echo "       Creating resource group '${RESOURCE_GROUP}' in '${LOCATION}'..."
  az group create \
    --name "${RESOURCE_GROUP}" \
    --location "${LOCATION}" \
    --output none
  echo "       Resource group created."
fi

# ---- Step 2: Deploy Bicep template ------------------------------------------
echo ""
echo "[2/5] Deploying Bicep template..."
echo "       Deployment name: ${DEPLOYMENT_NAME}"

az deployment group create \
  --resource-group "${RESOURCE_GROUP}" \
  --name "${DEPLOYMENT_NAME}" \
  --template-file "${TEMPLATE_FILE}" \
  --parameters "@${PARAMETERS_FILE}" \
  --output none

echo "       Deployment succeeded."

# ---- Step 3: Retrieve outputs ------------------------------------------------
echo ""
echo "[3/5] Retrieving deployment outputs..."

STORAGE_ACCOUNT=$(az deployment group show \
  --resource-group "${RESOURCE_GROUP}" \
  --name "${DEPLOYMENT_NAME}" \
  --query "properties.outputs.storageAccountName.value" \
  --output tsv)

REGISTRY_URL=$(az deployment group show \
  --resource-group "${RESOURCE_GROUP}" \
  --name "${DEPLOYMENT_NAME}" \
  --query "properties.outputs.registryUrl.value" \
  --output tsv)

BLOB_ENDPOINT=$(az deployment group show \
  --resource-group "${RESOURCE_GROUP}" \
  --name "${DEPLOYMENT_NAME}" \
  --query "properties.outputs.blobEndpoint.value" \
  --output tsv)

echo "       Storage Account : ${STORAGE_ACCOUNT}"
echo "       Registry URL    : ${REGISTRY_URL}"
echo "       Blob Endpoint   : ${BLOB_ENDPOINT}"

# ---- Step 4: Enable static website hosting -----------------------------------
echo ""
echo "[4/5] Enabling static website hosting with index document 'index.html'..."

az storage blob service-properties update \
  --account-name "${STORAGE_ACCOUNT}" \
  --static-website \
  --index-document "index.html" \
  --auth-mode key \
  --output none

echo "       Static website hosting enabled."

# ---- Step 5: Write config.sh -------------------------------------------------
echo ""
echo "[5/5] Writing config to '${CONFIG_FILE}'..."

cat > "${CONFIG_FILE}" <<EOF
# Auto-generated by deploy.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Source this file to set registry environment variables:
#   source infrastructure/config.sh

export STORAGE_ACCOUNT="${STORAGE_ACCOUNT}"
export CONTAINER_NAME='\$web'
export REGISTRY_URL="${REGISTRY_URL}"
export BLOB_ENDPOINT="${BLOB_ENDPOINT}"
EOF

echo "       Config written. Source it with:"
echo "         source ${CONFIG_FILE}"

echo ""
echo "============================================"
echo "  Deployment complete!"
echo "============================================"
